CREATE TYPE "TenantStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'ARCHIVED');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INVITED', 'SUSPENDED', 'DISABLED');
CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'INVITED', 'SUSPENDED');
CREATE TYPE "Role" AS ENUM ('PLATFORM_ADMIN', 'TENANT_MASTER', 'TENANT_MANAGER', 'CONSULTANT');
CREATE TYPE "AccessScope" AS ENUM ('TENANT', 'TEAM', 'ASSIGNED');
CREATE TYPE "TeamStatus" AS ENUM ('ACTIVE', 'ARCHIVED');
ALTER TABLE "Tenant" ADD COLUMN "slug" TEXT, ADD COLUMN "status" "TenantStatus" NOT NULL DEFAULT 'ACTIVE';
UPDATE "Tenant" SET "slug" = lower(regexp_replace("name", '[^a-zA-Z0-9]+', '-', 'g')) || '-' || substr("id", 1, 6);
ALTER TABLE "Tenant" ALTER COLUMN "slug" SET NOT NULL;
ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT, ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'INVITED';
UPDATE "User" SET "name" = COALESCE("name", split_part("email", '@', 1));
ALTER TABLE "User" ALTER COLUMN "name" SET NOT NULL;
ALTER TABLE "Membership" ADD COLUMN "status" "MembershipStatus" NOT NULL DEFAULT 'INVITED', ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Membership" ALTER COLUMN "role" TYPE "Role" USING "role"::"Role";
ALTER TABLE "AuditEvent" RENAME COLUMN "event" TO "action";
ALTER TABLE "AuditEvent" RENAME COLUMN "actorId" TO "actorUserId";
ALTER TABLE "AuditEvent" ADD COLUMN "entityType" TEXT NOT NULL DEFAULT 'unknown', ADD COLUMN "entityId" TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE "OutboxEvent" RENAME COLUMN "type" TO "eventType";
ALTER TABLE "OutboxEvent" RENAME COLUMN "occurredAt" TO "createdAt";
ALTER TABLE "OutboxEvent" ADD COLUMN "aggregateType" TEXT NOT NULL DEFAULT 'unknown', ADD COLUMN "lastError" TEXT, ADD COLUMN "lockedAt" TIMESTAMP(3);
UPDATE "OutboxEvent" SET "aggregateId" = "id" WHERE "aggregateId" IS NULL;
ALTER TABLE "OutboxEvent" ALTER COLUMN "aggregateId" SET NOT NULL;
CREATE TABLE "Team" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "status" "TeamStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Team_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TeamMember" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "teamId" TEXT NOT NULL, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TeamMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InviteToken" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InviteToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Tenant_slug_key" ON "Tenant"("slug");
CREATE INDEX "Tenant_status_idx" ON "Tenant"("status");
CREATE INDEX "Membership_tenantId_role_idx" ON "Membership"("tenantId", "role");
CREATE UNIQUE INDEX "Team_id_tenantId_key" ON "Team"("id", "tenantId");
CREATE INDEX "Team_tenantId_idx" ON "Team"("tenantId");
CREATE INDEX "Team_tenantId_status_idx" ON "Team"("tenantId", "status");
CREATE UNIQUE INDEX "TeamMember_teamId_userId_key" ON "TeamMember"("teamId", "userId");
CREATE INDEX "TeamMember_teamId_idx" ON "TeamMember"("teamId"); CREATE INDEX "TeamMember_userId_idx" ON "TeamMember"("userId"); CREATE INDEX "TeamMember_tenantId_idx" ON "TeamMember"("tenantId");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash"); CREATE INDEX "Session_userId_idx" ON "Session"("userId"); CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE UNIQUE INDEX "InviteToken_tokenHash_key" ON "InviteToken"("tokenHash"); CREATE INDEX "InviteToken_tenantId_idx" ON "InviteToken"("tenantId"); CREATE INDEX "InviteToken_userId_idx" ON "InviteToken"("userId"); CREATE INDEX "InviteToken_expiresAt_idx" ON "InviteToken"("expiresAt");
CREATE INDEX "AuditEvent_actorUserId_idx" ON "AuditEvent"("actorUserId"); CREATE INDEX "AuditEvent_action_idx" ON "AuditEvent"("action");
DROP INDEX "OutboxEvent_processedAt_occurredAt_idx"; DROP INDEX "OutboxEvent_tenantId_occurredAt_idx";
CREATE INDEX "OutboxEvent_processedAt_idx" ON "OutboxEvent"("processedAt"); CREATE INDEX "OutboxEvent_createdAt_idx" ON "OutboxEvent"("createdAt"); CREATE INDEX "OutboxEvent_tenantId_idx" ON "OutboxEvent"("tenantId"); CREATE INDEX "OutboxEvent_eventType_idx" ON "OutboxEvent"("eventType");
ALTER TABLE "Membership" DROP CONSTRAINT "Membership_tenantId_fkey", DROP CONSTRAINT "Membership_userId_fkey";
ALTER TABLE "AuditEvent" DROP CONSTRAINT "AuditEvent_tenantId_fkey"; ALTER TABLE "OutboxEvent" DROP CONSTRAINT "OutboxEvent_tenantId_fkey";
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Team" ADD CONSTRAINT "Team_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TeamMember" ADD CONSTRAINT "TeamMember_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "TeamMember_teamId_tenantId_fkey" FOREIGN KEY ("teamId", "tenantId") REFERENCES "Team"("id", "tenantId") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "TeamMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InviteToken" ADD CONSTRAINT "InviteToken_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "InviteToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "AuditEvent_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OutboxEvent" ADD CONSTRAINT "OutboxEvent_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
